FROM golang:1.18-alpine3.13 as builder

WORKDIR /app
COPY . .
RUN go build -o simplebank main.go

FROM alpine:3.13
COPY .env /app/.env
COPY --from=builder /app/simplebank .
EXPOSE 2207
CMD ["./simplebank"]    